#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
    use net
}


PIDDIR=/var/run/local
PIDFILE=$PIDDIR/cassandra.pid
[ -d $PIDDIR ] || mkdir -m=777 $PIDDIR


start() {
    ebegin "Starting Apache Cassandra"
    start-stop-daemon --start --user cassandra --exec /opt/cassandra/bin/cassandra --background --pidfile "$PIDFILE" -- -p $PIDFILE
    eend $?
}

stop() {
    ebegin "Stopping Apache Cassandra"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    eend $?
}

