#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
    use net
}


PIDFILE=/var/tmp/cassandra/cassandra.pid
DAEMON=/opt/cassandra/bin/cassandra
DAEMON_OPTS="-p $PIDFILE"
USER="cassandra"

start() {
    ebegin "Starting Apache Cassandra"
    . /opt/cassandra/conf/cassandra-env.sh
    start-stop-daemon --start --user $USER --exec $DAEMON --background --pidfile "$PIDFILE" -- $DAEMON_OPTS
    eend $?
}

stop() {
    ebegin "Stopping Apache Cassandra"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    eend $?
}

