#!/sbin/runscript

PIDFILE=/var/tmp/cassandra/cassandra.pid
DAEMON=/opt/cassandra/bin/cassandra
DAEMON_OPTS="-p $PIDFILE"
USER="cassandra"

. /opt/cassandra/conf/cassandra-env.sh

start() {
    ebegin "Starting Apache Cassandra"
    start-stop-daemon --start --user $USER --exec $DAEMON --background --pidfile "$PIDFILE" -- $DAEMON_OPTS >/dev/null
    eend $?
}

stop() {
    ebegin "Stopping Apache Cassandra"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    eend $?
}

